# Form implementation generated from reading ui file 'D:\Studying_Coding\ML_K23416\ss05_0810_retail\retail_project\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(593, 292)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(250, 30, 301, 201))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Email = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_Email.setGeometry(QtCore.QRect(10, 50, 271, 22))
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_Password.setGeometry(QtCore.QRect(10, 100, 271, 22))
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.checkBox_SaveLogin = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox_SaveLogin.setGeometry(QtCore.QRect(10, 130, 151, 20))
        self.checkBox_SaveLogin.setObjectName("checkBox_SaveLogin")
        self.pushButton_Login = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Login.setGeometry(QtCore.QRect(30, 160, 93, 28))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Studying_Coding\\ML_K23416\\ss05_0810_retail\\retail_project\\ui\\../images/icon_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Login.setIcon(icon)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.pushButton_Exit = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_Exit.setGeometry(QtCore.QRect(160, 160, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Studying_Coding\\ML_K23416\\ss05_0810_retail\\retail_project\\ui\\../images/icon_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Exit.setIcon(icon1)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 211, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("D:\\Studying_Coding\\ML_K23416\\ss05_0810_retail\\retail_project\\ui\\../images/z6966680334342_f8ccd842a360292e803daa3fc96b4e50.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 593, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_Exit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login - Japan DO"))
        self.groupBox.setTitle(_translate("MainWindow", "Login System:"))
        self.label.setText(_translate("MainWindow", "Email:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.lineEdit_Email.setText(_translate("MainWindow", "obama@gmail.com"))
        self.lineEdit_Password.setText(_translate("MainWindow", "123"))
        self.checkBox_SaveLogin.setText(_translate("MainWindow", "Save login information"))
        self.pushButton_Login.setText(_translate("MainWindow", "Login"))
        self.pushButton_Login.setShortcut(_translate("MainWindow", "Return"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
